// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.example.bookservice;

public final class BookServiceProto {
  private BookServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexBookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexBookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateBookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateBookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexBookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IndexBookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateBookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateBookResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchBooksRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchBooksRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Book_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SearchBooksResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SearchBooksResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022book_service.proto\"Z\n\020IndexBookRequest" +
      "\022\016\n\006bookID\030\001 \001(\t\022\021\n\tbookTitle\030\002 \001(\t\022\016\n\006a" +
      "uthor\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"[\n\021Upda" +
      "teBookRequest\022\016\n\006bookID\030\001 \001(\t\022\021\n\tbookTit" +
      "le\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\022\023\n\013description\030" +
      "\004 \001(\t\"$\n\021IndexBookResponse\022\017\n\007message\030\001 " +
      "\001(\t\"%\n\022UpdateBookResponse\022\017\n\007message\030\001 \001" +
      "(\t\"K\n\022SearchBooksRequest\022\r\n\005query\030\001 \001(\t\022" +
      "\023\n\013page_number\030\002 \001(\005\022\021\n\tpage_size\030\003 \001(\005\"" +
      "N\n\004Book\022\016\n\006bookID\030\001 \001(\t\022\021\n\tbookTitle\030\002 \001" +
      "(\t\022\016\n\006author\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"" +
      "+\n\023SearchBooksResponse\022\024\n\005books\030\001 \003(\0132\005." +
      "Book2\264\001\n\013BookService\0222\n\tIndexBook\022\021.Inde" +
      "xBookRequest\032\022.IndexBookResponse\0225\n\nUpda" +
      "teBook\022\022.UpdateBookRequest\032\023.UpdateBookR" +
      "esponse\022:\n\013SearchBooks\022\023.SearchBooksRequ" +
      "est\032\024.SearchBooksResponse0\001B-\n\027com.examp" +
      "le.bookserviceB\020BookServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IndexBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IndexBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexBookRequest_descriptor,
        new java.lang.String[] { "BookID", "BookTitle", "Author", "Description", });
    internal_static_UpdateBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateBookRequest_descriptor,
        new java.lang.String[] { "BookID", "BookTitle", "Author", "Description", });
    internal_static_IndexBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_IndexBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IndexBookResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_UpdateBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateBookResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_SearchBooksRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SearchBooksRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchBooksRequest_descriptor,
        new java.lang.String[] { "Query", "PageNumber", "PageSize", });
    internal_static_Book_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Book_descriptor,
        new java.lang.String[] { "BookID", "BookTitle", "Author", "Description", });
    internal_static_SearchBooksResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SearchBooksResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SearchBooksResponse_descriptor,
        new java.lang.String[] { "Books", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
