// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.example.bookservice;

public interface IndexBookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IndexBookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bookID = 1;</code>
   */
  java.lang.String getBookID();
  /**
   * <code>string bookID = 1;</code>
   */
  com.google.protobuf.ByteString
      getBookIDBytes();

  /**
   * <code>string bookTitle = 2;</code>
   */
  java.lang.String getBookTitle();
  /**
   * <code>string bookTitle = 2;</code>
   */
  com.google.protobuf.ByteString
      getBookTitleBytes();

  /**
   * <code>string author = 3;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 3;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string description = 4;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();
}
