// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.example.bookservice;

public interface SearchBooksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SearchBooksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<com.example.bookservice.Book> 
      getBooksList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  com.example.bookservice.Book getBooks(int index);
  /**
   * <code>repeated .Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<? extends com.example.bookservice.BookOrBuilder> 
      getBooksOrBuilderList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  com.example.bookservice.BookOrBuilder getBooksOrBuilder(
      int index);
}
