// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.example.bookservice;

public interface UpdateBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
