// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_manager_service.proto

package com.example.usermanager;

public interface PermissionCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PermissionCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string resource = 2;</code>
   */
  java.lang.String getResource();
  /**
   * <code>string resource = 2;</code>
   */
  com.google.protobuf.ByteString
      getResourceBytes();
}
