// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_manager_service.proto

package com.example.usermanager;

public interface PermissionCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PermissionCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool hasPermission = 1;</code>
   */
  boolean getHasPermission();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
