// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_manager_service.proto

package com.example.usermanager;

public final class UserManagerServiceProto {
  private UserManagerServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserAuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserAuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserAuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserAuthenticateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PermissionCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PermissionCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PermissionCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PermissionCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032user_manager_service.proto\"=\n\027UserAuth" +
      "enticateRequest\022\020\n\010userName\030\001 \001(\t\022\020\n\010pas" +
      "sword\030\002 \001(\t\"B\n\030UserAuthenticateResponse\022" +
      "\025\n\rauthenticated\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"" +
      "<\n\026PermissionCheckRequest\022\020\n\010userName\030\001 " +
      "\001(\t\022\020\n\010resource\030\002 \001(\t\"A\n\027PermissionCheck" +
      "Response\022\025\n\rhasPermission\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t2\243\001\n\022UserManagerService\022G\n\020UserA" +
      "uthenticate\022\030.UserAuthenticateRequest\032\031." +
      "UserAuthenticateResponse\022D\n\017PermissionCh" +
      "eck\022\027.PermissionCheckRequest\032\030.Permissio" +
      "nCheckResponseB4\n\027com.example.usermanage" +
      "rB\027UserManagerServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserAuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserAuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserAuthenticateRequest_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_UserAuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserAuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserAuthenticateResponse_descriptor,
        new java.lang.String[] { "Authenticated", "Message", });
    internal_static_PermissionCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PermissionCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PermissionCheckRequest_descriptor,
        new java.lang.String[] { "UserName", "Resource", });
    internal_static_PermissionCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PermissionCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PermissionCheckResponse_descriptor,
        new java.lang.String[] { "HasPermission", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
