// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_integration_service.proto

package com.example.iot;

public interface DeviceControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeviceControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceId = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string deviceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string action = 2;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>double value = 3;</code>
   */
  double getValue();
}
