// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_integration_service.proto

package com.example.iot;

public interface DeviceControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeviceControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * DoorOpen, DoorClose, DoorLock
   * </pre>
   *
   * <code>string doorStatus = 2;</code>
   */
  java.lang.String getDoorStatus();
  /**
   * <pre>
   * DoorOpen, DoorClose, DoorLock
   * </pre>
   *
   * <code>string doorStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getDoorStatusBytes();
}
