// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_integration_service.proto

package com.example.iot;

public interface IoTDevMonitoringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IoTDevMonitoringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensorId = 1;</code>
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensorId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();

  /**
   * <code>string sensorType = 2;</code>
   */
  java.lang.String getSensorType();
  /**
   * <code>string sensorType = 2;</code>
   */
  com.google.protobuf.ByteString
      getSensorTypeBytes();

  /**
   * <code>string sensorStatus = 3;</code>
   */
  java.lang.String getSensorStatus();
  /**
   * <code>string sensorStatus = 3;</code>
   */
  com.google.protobuf.ByteString
      getSensorStatusBytes();

  /**
   * <code>double tempValue = 4;</code>
   */
  double getTempValue();

  /**
   * <code>double lightValue = 5;</code>
   */
  double getLightValue();

  /**
   * <code>double noiseLevel = 6;</code>
   */
  double getNoiseLevel();
}
