// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_integration_service.proto

package com.example.iot;

public interface IoTDevMonitoringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IoTDevMonitoringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensorId = 1;</code>
   */
  java.lang.String getSensorId();
  /**
   * <code>string sensorId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIdBytes();
}
