// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iot_integration_service.proto

package com.example.iot;

public final class IoTIntegrationServiceProto {
  private IoTIntegrationServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IoTDevMonitoringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IoTDevMonitoringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IoTDevMonitoringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IoTDevMonitoringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceControlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035iot_integration_service.proto\"+\n\027IoTDe" +
      "vMonitoringRequest\022\020\n\010sensorId\030\001 \001(\t\"\221\001\n" +
      "\030IoTDevMonitoringResponse\022\020\n\010sensorId\030\001 " +
      "\001(\t\022\022\n\nsensorType\030\002 \001(\t\022\024\n\014sensorStatus\030" +
      "\003 \001(\t\022\021\n\ttempValue\030\004 \001(\001\022\022\n\nlightValue\030\005" +
      " \001(\001\022\022\n\nnoiseLevel\030\006 \001(\001\"G\n\024DeviceContro" +
      "lRequest\022\020\n\010deviceId\030\001 \001(\t\022\016\n\006action\030\002 \001" +
      "(\t\022\r\n\005value\030\003 \001(\001\"<\n\025DeviceControlRespon" +
      "se\022\017\n\007message\030\001 \001(\t\022\022\n\ndoorStatus\030\002 \001(\t2" +
      "\244\001\n\025IoTIntegrationService\022K\n\024IoTDevMonit" +
      "oringServ\022\030.IoTDevMonitoringRequest\032\031.Io" +
      "TDevMonitoringResponse\022>\n\rDeviceControl\022" +
      "\025.DeviceControlRequest\032\026.DeviceControlRe" +
      "sponseB/\n\017com.example.iotB\032IoTIntegratio" +
      "nServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IoTDevMonitoringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IoTDevMonitoringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IoTDevMonitoringRequest_descriptor,
        new java.lang.String[] { "SensorId", });
    internal_static_IoTDevMonitoringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IoTDevMonitoringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IoTDevMonitoringResponse_descriptor,
        new java.lang.String[] { "SensorId", "SensorType", "SensorStatus", "TempValue", "LightValue", "NoiseLevel", });
    internal_static_DeviceControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DeviceControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceControlRequest_descriptor,
        new java.lang.String[] { "DeviceId", "Action", "Value", });
    internal_static_DeviceControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DeviceControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceControlResponse_descriptor,
        new java.lang.String[] { "Message", "DoorStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
